RevClothing/Models/Store.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RevClothing.Models
{
    public class Store
    {
        public List<Product> ProductList { get; set; }
        public List<Categoryclothes> CategoryList { get; set; }
    }
}

RevClothing/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using RevClothing.Models;
using RevClothing.Data;
using System.Diagnostics;




namespace RevClothing.Controllers

{

    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;
        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? c)
        {
            var products = _context.Products.Include(p => p.Category).ToList();
            if (c != null)
            {
                products = products.Where(p => p.CategoryID == (int)c).ToList();
            }
            var categories = _context.Category.Include(c => c.CategoryName).ToList();
            var record = new Store()
            {
                ProductList = products,
                CategoryList = categories
            };
            return View(record);
        }
    }        
    //[Authorize]
    //public IActionResult AddToCart(int? id, int? quantity)
    //{
    //    if(id == null)
    //    {
    //        return RedirectToAction("Index");
    //    }

    //}
}

RevClothing/Views/Store/Index.cshtml
@model RevClothing.Models.Store
@inject RevClothing.Data.ApplicationDbContext _context 

@{
    ViewData["Title"] = "My Store";
}

<div class="container">
    <div class="row">
        <div class="col-xl-3"> 
            <div class="card">
                <div class="list-group">
                    <a href="~/Store" class="list-group-item active d-flex justify-content-between align-items-center"
                       style="text-decoration:none;" aria-current="true"> All Categories <span class="badge badge-info badge-pill">
                        @Model.ProductList.Count
                        </span>
                    </a>
                    @foreach (var item in Model.CategoryList)
                    {
                        var totalRecords = _context.Products.Where(p => p.CategoryID == item.CategoryID).ToList().Count;
                        <a href="~/Store?c=@(item.CategoryID)" class="list-group-item d-flex justify-content-between align-items-center"
                           style="text-decoration:none;">
                            @item.CategoryName
                            <span class="badge badge-info-pill">@totalRecords  </span>
                        </a>
                    }
                </div>
            </div>
        </div>
 <div class="col-xl-9">      
            <div class="row">
                @foreach (var item in Model.ProductList.OrderBy(p => p.Price).ToList())
                {
                    <div class="col-4">
                        <div class="card" alt="@(item.ProductName)"
                             style="height:200px;object-fit:cover;object-position:center;">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">@(item.ProductName)</h5>
                            <p class="card=text">@(item.Category.CategoryName)</p>
                            <p class="card=text">@(item.Price.ToString("N"))</p>
                            <a href="@(Url.Action("Detail", "Store", new { id = item.ProductID }))"
                               class="btn btn-primary">See Details</a>
                        </div>
                    </div>
                    <br><br />
                }
           </div>
         </div>           
               
            
 </div>
  
</div>