RevClothing/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.EntityFrameworkCore;
using RevClothing.Data;
using RevClothing.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace RevClothing.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        [HttpPost]
        public IActionResult Childrens()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Home()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Mens()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Womens()
        {
            return View();
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RevClothing/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RevClothing.Data;
using RevClothing.Models;

namespace RevClothing.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var list = _context.Items.ToList();
            return View(list);
        }   
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Item record)
        {
            var item = new Item();
            item.Name = record.Name;
            item.code = record.code;
            item.Description = record.Description;
            item.Price = record.Price;
            item.DateAdded = DateTime.Now;
            item.Type = record.Type;

            _context.Items.Add(item);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var item = _context.Items.Where(i => i.ItemId == id).SingleOrDefault();
            if (item == null)
            {
                return RedirectToAction("Index");
            }

            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(int? id, Item record)
        {
            var item = _context.Items.Where(i => i.ItemId == id).SingleOrDefault();
            item.Name = record.Name;
            item.code = record.code;
            item.Description = record.Description;
            item.Price = record.Price;
            item.DateModified = DateTime.Now;
            item.Type = record.Type;

            _context.Items.Update(item);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var item = _context.Items.Where(i => i.ItemId == id).SingleOrDefault();
            if (item == null)
            {
                return RedirectToAction("Index");
            }

            _context.Items.Remove(item);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

RevClothing/Views/Home/Childrens.cshtml
@model RevClothing.Models.Product

@{
//ViewData["Title"] = "Childrens";
//Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - RevClothing</title>*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/datatable/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!--<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />-->
    <!-- Favicon-->
    <!--<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />-->
    <!-- Bootstrap icons-->
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />-->
    <!-- Core theme CSS (includes Bootstrap)-->
    <!--<link href="css/styles.css" rel="stylesheet" />-->
</head>
<body>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5" img src="~/images/baby2.jpg">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Children in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">Revel Clothing</p>
            </div>
        </div>
    </header>

    <!-- Section-->
    <div class="col mb-5">
        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Create">Post Your Own!</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">View Your Post!</a>
    </div>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/images/baby2.jpg" alt="..." />
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/images/baby.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container px-4 px-lg-5 mt-5">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Home">Go Back to Categories!</a>
            </div> 
        </div>
    </section>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

RevClothing/Views/Home/Home.cshtml
@model RevClothing.Models.Product
@*

*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - RevClothing</title>*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/datatable/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!--<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />-->
    <!-- Favicon-->
    <!--<link rel="icon" type="image/x-icon" href="assets/favicon.ico" />-->
    <!-- Bootstrap icons-->
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />-->
    <!-- Core theme CSS (includes Bootstrap)-->
    <!--<link href="css/styles.css" rel="stylesheet" />-->
</head>
<body>
    <div class="container">
        
            <main role="main" class="pb-3">


                <div class="text-center">
                    <h1 class="display-4">Welcome to Revella ClothingLine</h1>
                    <p class="dropdown-item-text">
                        Please select a Category.

                    </p>
                </div>
                </main>
      

            
    </div>
    <div class="row pad-top">

        <div class="col-lg-3  col-sm-6 img-thumbnail">
            <form asp-action="Childrens">
                <img src="/images/baby1.jpg" class="img-thumbnail img-fluid">
                <input class="btn btn-outline-success" type="submit" value="Childrens Apparel" />
            </form>
        </div>
        <div class="col-lg-3  col-sm-6 img-thumbnail">
            <form asp-action="Mens">
                <img src="/images/men1.jpg" class="img-thumbnail img-fluid">
                <input class="btn btn-outline-success" type="submit" value="Mens Apparel" />
            </form>
        </div>
        <div class="col-lg-3 col-sm-6 img-thumbnail">
            <form asp-action="Womens">
                <img src="/images/fem1.jpg" class="img-thumbnail img-fluid">
                <input class="btn btn-outline-success" type="submit" value="Womens Apparel" />
            </form>
        </div>
    </div>

</body>

</html>

RevClothing/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


    
    <div class="container">
        <main role="main" class="pb-3">

            <body>
                <div class="text-center">
                    <h1 class="display-4">Revella ClothingLine</h1>
                    <p class="dropdown-item-text">
                        The ultimate clothing to see the world in

                    </p>
                </div>
               
            </body>
            
         </main>
      </div>

RevClothing/Views/Home/Mens.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - RevClothing</title>*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/datatable/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Men in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">Revel Clothing</p>
            </div>
        </div>
    </header>

    <div class="col mb-5">
        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Create">Post Your Own!</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">View Your Post!</a>
    </div>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/images/men.jpg" alt="..." />
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/images/men2.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" asp-controller="Home" asp-action="Home">Back to Categories</button>
            </div>
        </div>
    </section>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

RevClothing/Views/Home/Womens.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - RevClothing</title>*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/datatable/css/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Women in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">Revel Clothing</p>
            </div>
        </div>
    </header>

    <div class="col mb-5">
        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Create">Post Your Own!</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">View Your Post!</a>
    </div>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/images/fem2.jpg" alt="..." />
                    </div>
                </div>
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="~/images/fem.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div>
                    <a asp-action="Home">Back to Categories</a>
                </div>
            </div>
        </div>
    </section>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>